-- MySQL Script generated by MySQL Workbench
-- Fri Aug 30 18:33:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Fabrica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fabrica` (
  `Id_fabrica` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Ubicacion` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_fabrica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `Dni_Empleado` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Puesto` VARCHAR(45) NULL,
  `Id_fabrica` INT NOT NULL,
  PRIMARY KEY (`Dni_Empleado`, `Id_fabrica`),
  CONSTRAINT `fk_Empleado_Fabrica`
    FOREIGN KEY (`Id_fabrica`)
    REFERENCES `mydb`.`Fabrica` (`Id_fabrica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Empleado_Fabrica_idx` ON `mydb`.`Empleado` (`Id_fabrica` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `Id_cliente` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Maquina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Maquina` (
  `Id_maquina` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Id_fabrica` INT NOT NULL,
  PRIMARY KEY (`Id_maquina`, `Id_fabrica`),
  CONSTRAINT `fk_Maquina_Fabrica1`
    FOREIGN KEY (`Id_fabrica`)
    REFERENCES `mydb`.`Fabrica` (`Id_fabrica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Maquina_Fabrica1_idx` ON `mydb`.`Maquina` (`Id_fabrica` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedidos` (
  `id_pedidos` INT NOT NULL,
  `Fecha` DATETIME NULL,
  `Id_cliente` INT NOT NULL,
  `Dni_Empleado` INT NOT NULL,
  `Id_fabrica` INT NOT NULL,
  PRIMARY KEY (`id_pedidos`, `Id_cliente`, `Dni_Empleado`, `Id_fabrica`),
  CONSTRAINT `fk_Pedidos_Cliente1`
    FOREIGN KEY (`Id_cliente`)
    REFERENCES `mydb`.`Cliente` (`Id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Empleado1`
    FOREIGN KEY (`Dni_Empleado` , `Id_fabrica`)
    REFERENCES `mydb`.`Empleado` (`Dni_Empleado` , `Id_fabrica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pedidos_Cliente1_idx` ON `mydb`.`Pedidos` (`Id_cliente` ASC) VISIBLE;

CREATE INDEX `fk_Pedidos_Empleado1_idx` ON `mydb`.`Pedidos` (`Dni_Empleado` ASC, `Id_fabrica` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `id_Producto` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Precio` FLOAT NULL,
  PRIMARY KEY (`id_Producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto_Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto_Pedidos` (
  `Id_Producto` INT NOT NULL,
  `Id_pedidos` INT NOT NULL,
  PRIMARY KEY (`Id_Producto`, `Id_pedidos`),
  CONSTRAINT `fk_Producto_has_Pedidos_Producto1`
    FOREIGN KEY (`Id_Producto`)
    REFERENCES `mydb`.`Producto` (`id_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Pedidos_Pedidos1`
    FOREIGN KEY (`Id_pedidos`)
    REFERENCES `mydb`.`Pedidos` (`id_pedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Producto_has_Pedidos_Pedidos1_idx` ON `mydb`.`Producto_Pedidos` (`Id_pedidos` ASC) VISIBLE;

CREATE INDEX `fk_Producto_has_Pedidos_Producto1_idx` ON `mydb`.`Producto_Pedidos` (`Id_Producto` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
